---
title: "SEDS Updated Table 5.1"
author: "Megan Hollister"
date: "7/25/2018"
output:
  html_document:
    code_folding: hide
header-includes:
  - \usepackage{color}
---

```{r, include=FALSE}
require(tgsify)
```

#Christina's code
```{r include=FALSE}
library(locfdr)
library(splines)

load("prostz.RData")
# head(prostz) # z-stats

locfdrplot <- locfdr(prostz)

## to make results consistent with the book
which(abs(prostz)> 4.5)
prostz[610]
prostz[1720]
prostzcut <- prostz[prostz<=4.5 & prostz>=-4.5] # omitting two huge values
# It appears as though he still uses N=6033 instead of N=6031


######################
## Lindsey's method ##
######################

bin<- 90 # number of bins
# lo <- min(prostz)
# up <- max(prostz)
N<- length(prostz) # number of cases=6033, used to match his results 
d<- 0.1 # bin width
df<- 7 # J= degrees of freedom

breaks <- seq(-4.5, 4.5, d)
zh <- hist(prostzcut, breaks = breaks, plot = F)
y <- zh$counts # y = the number of counts in each of the 90 bins
x <- zh$mids # note this equals the midpoints x of each bin
head(x)
# Another way to get the midpoints:
# x <- (breaks[-1] + breaks[-length(breaks)])/2
K <- length(y) # 90
k <- seq(K) # seq from 1:90
# X<- cbind(1,ns(x,df=df))
# X<- cbind(1,poly(x,df=df))
yhat <- glm(y ~ ns(x,df=df), poisson)$fit # the expected value of Y, i.e. yhat = N*d*f(x_k)
Fl <- cumsum(yhat) #empirical cdf
Fr <- cumsum(rev(yhat))
pi0 <- 0.932 # prior probability of null (from page 71 in Efron)

#####################
## pg 71 histogram ##
#####################
hi<- hist(prostzcut,breaks=breaks,xlab="z values",ylab="counts")
# add dashed curve- the scaled estimate. Trial and error yielded 540.
lines(x,540*dnorm(x),lty="dashed", lwd=2)
# add thick solid curve- estimate for mixture density
lines(x,yhat,lwd=3)

# Try with pi0*d*N as scale (looks much more similar to locfdr plot)
hi<- hist(prostzcut,breaks=breaks,xlab="z values",ylab="counts")
lines(x,yhat,lwd=3)
lines(x,pi0*d*N*dnorm(x),lty="dashed",col="red",lwd=3)
# lines(x,0.10*6033*0.932*dnorm(x),lty=2,col="red")

# area under the curve == sum of area of histogram bins
height<- hi$counts
sum(height*d) # = 6031*.1
```
```{r}
###############
## Table 5.1 ##
###############
# Now try adding back the 2 omitted observations into bin 90:
#y[90]  currently 1 observation in bin 90
y[90]<- 3
#yhat<- glm(y~ns(x,df=df),poisson)$fit # the expected value of Y, i.e. yhat
e0 <- N*d*pi0*dnorm(x) # expected null count
fdrBar <- e0/y
fdrHat <- e0/yhat
table2 <- cbind(k,x,e0,y,fdrBar,yhat,fdrHat) # recreating table 5.1
round(table2[76:83,],3)
# Now the table (specifically column yhat) matches book perfectly.

#################################
## Recreate Figure 5.2:        ##
## local fdr for prostate data ##
#################################
## fdrHat vs midpoints x

#plot(x,fdrHat,xlab="midpoints x_k",ylab="estimated local fdr fdrHat",lwd=2,type="l")
#abline(v=0,lty="dotted")
#abline(h=0.2, col="grey")
####
# f<- glm(y~ns(x,df=df),poisson)
# predict(f,type="link")
# l<- log(f)
# D <- (y - f)/(f + 1)^0.5 # standardizing
# D <- sum(D[2:(K - 1)]^2)/(K - 2 - df)  # sum of Poisson deviances: measure of discrepancy between observed and fitted value
```
#Tom's code
```{r include=FALSE}
library(magrittr)

pd <- prostz
status <- pd %>% colnames %>% as.numeric %>% `[`(c("No cancer","Cancer"), .)
tvalue <- function(x, g) t.test(x ~ g) #%>% le("statistic")
#zs <- pd %>% apply(1, tvalue, g = status) %>% pt(100) %>% qnorm

zs <- prostzcut
suppressMessages(require(splines))
pz <- ecdf(c(-10, zs, 10))(zs)

#plotstyle(style = upright)
par(mar = c(2,2,2,2))
plot(zs, pz, col = "#0E0879")

logodds <- function(x) log(x/(1-x))
sigmoid <- function(x) 1/(1+exp(-x))

l1 <- lm(logodds(pz) ~ poly(zs, degree = 3))
points(zs, sigmoid(l1$fitted), col = "purple")

ws <- cut(zs, breaks = seq(-4.5, 4.5, by = .1))
labs <- levels(ws)
lo <- labs %>% sub("\\((.+),.*", "\\1", .) %>% as.numeric
up <- labs %>% sub("[^,]*,([^]]*)\\]", "\\1", .) %>% as.numeric

p_lo <- predict(l1,newdata=data.frame(zs = lo)) %>% sigmoid
p_up <- predict(l1,newdata=data.frame(zs = up)) %>% sigmoid
phat <- p_up - p_lo
nhat <- phat * length(zs)
mp <- .5*lo + .5*up
```

```{r}
###################################
#######Change width of bins########
###################################

#Smaller Bin Size
bin2<- 180 # number of bins
N<- length(prostz) # number of cases=6033, used to match his results 
d2<- 0.05 # bin width
df<- 7 # J= degrees of freedom

breaks2 <- seq(-4.5, 4.5, d2)
zh2 <- hist(prostzcut, breaks = breaks2, plot = F)
y2 <- zh2$counts # y = the number of counts in each of the 90 bins
x2 <- zh2$mids # note this equals the midpoints x of each bin
yhat2 <- glm(y2 ~ ns(x2,df=df), poisson)$fit
e02 <- N*d2*pi0*dnorm(x2)

ws2 <- cut(zs, breaks = seq(-4.5, 4.5, by = d2))
labs2 <- levels(ws2)
lo2 <- labs2 %>% sub("\\((.+),.*", "\\1", .) %>% as.numeric
up2 <- labs2 %>% sub("[^,]*,([^]]*)\\]", "\\1", .) %>% as.numeric

p_lo2 <- predict(l1,newdata=data.frame(zs = lo2)) %>% sigmoid
p_up2 <- predict(l1,newdata=data.frame(zs = up2)) %>% sigmoid
phat2 <- p_up2 - p_lo2
nhat2 <- phat2 * length(zs)
mp2 <- .5*lo2 + .5*up2

#####Larger Bin size
bin3<- 36 # number of bins
N<- length(prostz) # number of cases=6033, used to match his results 
d3<- 0.25 # bin width
df<- 7 # J= degrees of freedom

breaks3 <- seq(-4.5, 4.5, d3)
zh3 <- hist(prostzcut, breaks = breaks3, plot = F)
y3 <- zh3$counts # y = the number of counts in each of the 90 bins
x3 <- zh3$mids # note this equals the midpoints x of each bin
yhat3 <- glm(y3 ~ ns(x3,df=df), poisson)$fit
e03 <- N*d3*pi0*dnorm(x3)

ws3 <- cut(zs, breaks = seq(-4.5, 4.5, by = .d3))
labs3 <- levels(ws3)
lo3 <- labs3 %>% sub("\\((.+),.*", "\\1", .) %>% as.numeric
up3 <- labs3 %>% sub("[^,]*,([^]]*)\\]", "\\1", .) %>% as.numeric

p_lo3 <- predict(l1,newdata=data.frame(zs = lo3)) %>% sigmoid
p_up3 <- predict(l1,newdata=data.frame(zs = up3)) %>% sigmoid
phat3 <- p_up3 - p_lo3
nhat3 <- phat3 * length(zs)
mp3 <- .5*lo3 + .5*up3
```

```{r}
hist(zs, breaks = 90, col = "#ad000070",border = "white")
lines(mp, yhat, col = "purple", lwd = 3)
lines(mp, nhat, col = "darkgreen", lwd = 3)
box()
legend("topleft", c("Lindsay's","ECDF"), lwd = 3, col = c("purple","darkgreen"), bty = 'n')

#Change bin size
hist(zs, breaks = 180, col = "#ad000070",border = "white", main="Histogram with Smaller Bins")
lines(mp2, yhat2, col = "purple", lwd = 3)
lines(mp2, nhat2, col = "darkgreen", lwd = 3)
box()
legend("topleft", c("Lindsay's","ECDF"), lwd = 3, col = c("purple","darkgreen"), bty = 'n')

hist(zs, breaks = 36, col = "#ad000070",border = "white", ylim=c(0,600), main = "Histogram with Larger Bins")
lines(mp3, yhat3, col = "purple", lwd = 3)
lines(mp3, nhat3, col = "darkgreen", lwd = 3)
box()
legend("topleft", c("Lindsay's","ECDF"), lwd = 3, col = c("purple","darkgreen"), bty = 'n')
```

#Megan's additional code and graph
```{r}
ytilde <- nhat
fdrtilde <- e0/ytilde

ytilde2 <- nhat2
fdrtilde2 <- e02/ytilde2
edit2 <- ytilde2[seq(1,length(ytilde2),2)]

ytilde3 <- nhat3
fdrtilde3 <- e03/ytilde3

table3 <- cbind(table2, ytilde, fdrtilde) 
table4 <- cbind(x2, ytilde2, fdrtilde2) 
table5 <- cbind(x3, ytilde3, fdrtilde3) 

round(table3[76:83,],3)
round(table4[154:166,],3)
round(table5[28:36,],3)

plot(x, fdrBar, type = "l")
lines(x,fdrHat, col="red")
lines(x, fdrtilde, col="blue")
lines(x2, fdrtilde2, col="green")
lines(x3, fdrtilde3, col="pink")
legend("topright", c("fdrBar","fdrHat", "fdrTilde", "fdrTilde2", "fdrTilde3"), lwd = 3, col = c("black","red", "blue", "green", "pink"), bty = 'n')

plot(x, fdrHat, col="red", type = "l", ylim = c(0.96,0.975), xlim= c(-0.1,0.1), lwd=4)
lines(x, fdrtilde, col="blue", lwd=4)
lines(x2, fdrtilde2, col="green", lwd=4)
lines(x3, fdrtilde3, col="pink", lwd=4)
legend("topright", c("fdrHat", "fdrTilde", "fdrTilde2", "fdrTilde3"), lwd = 3, col = c("red", "blue", "green", "pink"), bty = 'n')
```


